// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBezkmuVqoejS_gLbcZZ5-8Ox3_SnA3KF0',
    appId: '1:926223382742:web:24a5ae7932ccdf2971f177',
    messagingSenderId: '926223382742',
    projectId: 'fire-7a61c',
    authDomain: 'fire-7a61c.firebaseapp.com',
    storageBucket: 'fire-7a61c.appspot.com',
    measurementId: 'G-1MC7WBM1Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSz5NYMuoJgb3ra_9IKtysjKolrAEWM_4',
    appId: '1:926223382742:android:35397bb2f5f16d6871f177',
    messagingSenderId: '926223382742',
    projectId: 'fire-7a61c',
    storageBucket: 'fire-7a61c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraOMaeC3yyRgdFxvpTTFE33VXiRlU6io',
    appId: '1:926223382742:ios:3324931ac783445d71f177',
    messagingSenderId: '926223382742',
    projectId: 'fire-7a61c',
    storageBucket: 'fire-7a61c.appspot.com',
    iosBundleId: 'cogfm.example.fire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAraOMaeC3yyRgdFxvpTTFE33VXiRlU6io',
    appId: '1:926223382742:ios:3324931ac783445d71f177',
    messagingSenderId: '926223382742',
    projectId: 'fire-7a61c',
    storageBucket: 'fire-7a61c.appspot.com',
    iosBundleId: 'cogfm.example.fire',
  );
}
